spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/artistas_db
    username: postgres
    password: postgres

  jpa:
    show-sql: true

minio:
  access-key: minioadmin
  secret-key: minioadmin
  endpoint: http://localhost:9000

logging:
  level:
    root: DEBUG
